apiVersion: v1
kind: ConfigMap
metadata:
  name: buildbarn-config-g99g2mcfg6
  namespace: buildbarn
data:
  common.libsonnet: |
    {
      blobstore: {
        contentAddressableStorage: {
          sharding: {
            shards: {
              "0": {
                backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },
                weight: 1,
              },
              "1": {
                backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },
                weight: 1,
              },
            },
          },
        },
        actionCache: {
          completenessChecking: {
            backend: {
              sharding: {
                shards: {
                  "0": {
                    backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },
                    weight: 1,
                  },
                  "1": {
                    backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },
                    weight: 1,
                  },
                },
              },
            },
            maximumTotalTreeSizeBytes: 64 * 1024 * 1024,
          },
        },
      },
      fileSystemAccessCache: {
        sharding: {
          shards: {
            "0": {
              backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },
              weight: 1,
            },
            "1": {
              backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },
              weight: 1,
            },
          },
        },
      },
      browserUrl: 'http://bb-browser.example.com:80',
      maximumMessageSizeBytes: 2 * 1024 * 1024,
      global: {
        diagnosticsHttpServer: {
          httpServers: [{
            listenAddresses: [':9980'],
            authenticationPolicy: { allow: {} },
          }],
          enablePrometheus: true,
          enablePprof: true,
          enableActiveSpans: true,
        },
      },
    }
  frontend.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8980'],
        authenticationPolicy: { allow: {} },
      }],
      schedulers: {
        '': {
          endpoint: {
            address: 'scheduler:8982',
            addMetadataJmespathExpression: {
              expression: |||
                {
                  "build.bazel.remote.execution.v2.requestmetadata-bin": incomingGRPCMetadata."build.bazel.remote.execution.v2.requestmetadata-bin"
                }
              |||,
            },
          },
        },
      },
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      contentAddressableStorage: {
        backend: common.blobstore.contentAddressableStorage,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
        findMissingAuthorizer: { allow: {} },
      },
      actionCache: {
        backend: common.blobstore.actionCache,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      fileSystemAccessCache: {
        backend: common.fileSystemAccessCache,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      executeAuthorizer: { allow: {} },
    }
  storage.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8981'],
        authenticationPolicy: { allow: {} },
      }],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      contentAddressableStorage: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-cas/key_location_map',
                sizeBytes: 400 * 1024 * 1024,
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 3,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-cas/blocks',
                  sizeBytes: 32 * 1024 * 1024 * 1024,
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-cas/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
        findMissingAuthorizer: { allow: {} },
      },
      actionCache: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-ac/key_location_map',
                sizeBytes: 1024 * 1024,
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-ac/blocks',
                  sizeBytes: 20 * 1024 * 1024,
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-ac/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      fileSystemAccessCache:  {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-fsac/key_location_map',
                sizeBytes: 1024 * 1024,
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-fsac/blocks',
                  sizeBytes: 20 * 1024 * 1024,
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-fsac/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
    }
  browser.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      httpServers: [{
        listenAddresses: [':7984'],
        authenticationPolicy: { allow: {} },
      }],
      global: common.global,
      authorizer: { allow: {} },
      requestMetadataLinksJmespathExpression: { expression: '`{}`' },
    }
  runner-ubuntu22-04.jsonnet: |
    local common = import 'common.libsonnet';

    {
      buildDirectoryPath: '/worker/build',
      // TODO: global: common.global,
      grpcServers: [{
        listenPaths: ['/worker/runner'],
        authenticationPolicy: { allow: {} },
      }],
    }
  scheduler.jsonnet: |
    local common = import 'common.libsonnet';

    {
      adminHttpServers: [{
        listenAddresses: [':7982'],
        authenticationPolicy: { allow: {} },
      }],
      clientGrpcServers: [{
        listenAddresses: [':8982'],
        authenticationPolicy: { allow: {} },
      }],
      workerGrpcServers: [{
        listenAddresses: [':8983'],
        authenticationPolicy: { allow: {} },
      }],
      buildQueueStateGrpcServers: [{
        listenAddresses: [':8984'],
        authenticationPolicy: { allow: {} },
      }],
      browserUrl: common.browserUrl,
      contentAddressableStorage: common.blobstore.contentAddressableStorage,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      executeAuthorizer: { allow: {} },
      modifyDrainsAuthorizer: { allow: {} },
      killOperationsAuthorizer: { allow: {} },
      synchronizeAuthorizer: { allow: {} },
      actionRouter: {
        simple: {
          platformKeyExtractor: { action: {} },
          invocationKeyExtractors: [
            { correlatedInvocationsId: {} },
            { toolInvocationId: {} },
          ],
          initialSizeClassAnalyzer: {
            defaultExecutionTimeout: '1800s',
            maximumExecutionTimeout: '7200s',
          },
        },
      },
      platformQueueWithNoWorkersTimeout: '900s',
    }
  worker-ubuntu22-04.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      browserUrl: common.browserUrl,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      scheduler: { address: 'scheduler:8983' },
      global: common.global {
        setUmask: { umask: 0 },
      },
      buildDirectories: [{
        native: {
          buildDirectoryPath: '/worker/build',
          cacheDirectoryPath: '/worker/cache',
          maximumCacheFileCount: 10000,
          maximumCacheSizeBytes: 1024 * 1024 * 1024,
          cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
        },
        runners: [{
          endpoint: { address: 'unix:///worker/runner' },
          concurrency: 8,
          platform: {
            properties: [
              { name: 'OSFamily', value: 'linux' },
              { name: 'container-image', value: 'docker://ghcr.io/catthehacker/ubuntu:act-22.04@sha256:dd7654ffb01d5b7b54b23b9ce928a1f7f2d08c7b3d7e320b6574b55d7ccde78b' },
            ],
          },
          workerId: {
            pod: std.extVar('POD_NAME'),
            node: std.extVar('NODE_NAME'),
          },
        }],
      }],
      inputDownloadConcurrency: 10,
      outputUploadConcurrency: 11,
      directoryCache: {
        maximumCount: 1000,
        maximumSizeBytes: 1000 * 1024,
        cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
      },
    }
