apiVersion: v1
data:
  browser.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      httpServers: [{
        listenAddresses: [':7984'],
        authenticationPolicy: { allow: {} },
      }],
      global: common.global,
      authorizer: { allow: {} },
      requestMetadataLinksJmespathExpression: { expression: '`{}`' },
    }
  common.libsonnet: |
    {
      blobstore: {
        contentAddressableStorage: {
          sharding: {
            shards: {
              "0": {
                backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },
                weight: 1,
              },
              "1": {
                backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },
                weight: 1,
              },
            },
          },
        },
        actionCache: {
          completenessChecking: {
            backend: {
              sharding: {
                shards: {
                  "0": {
                    backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },
                    weight: 1,
                  },
                  "1": {
                    backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },
                    weight: 1,
                  },
                },
              },
            },
            maximumTotalTreeSizeBytes: 64 * 1024 * 1024,
          },
        },
      },
      fileSystemAccessCache: {
        sharding: {
          shards: {
            "0": {
              backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },
              weight: 1,
            },
            "1": {
              backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },
              weight: 1,
            },
          },
        },
      },
      browserUrl: 'http://bb-browser.example.com:80',
      maximumMessageSizeBytes: 2 * 1024 * 1024,
      global: {
        diagnosticsHttpServer: {
          httpServers: [{
            listenAddresses: [':9980'],
            authenticationPolicy: { allow: {} },
          }],
          enablePrometheus: true,
          enablePprof: true,
          enableActiveSpans: true,
        },
      },
    }
  frontend.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8980'],
        authenticationPolicy: { allow: {} },
      }],
      schedulers: {
        '': {
          endpoint: {
            address: 'scheduler:8982',
            addMetadataJmespathExpression: {
              expression: |||
                {
                  "build.bazel.remote.execution.v2.requestmetadata-bin": incomingGRPCMetadata."build.bazel.remote.execution.v2.requestmetadata-bin"
                }
              |||,
            },
          },
        },
      },
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      contentAddressableStorage: {
        backend: common.blobstore.contentAddressableStorage,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
        findMissingAuthorizer: { allow: {} },
      },
      actionCache: {
        backend: common.blobstore.actionCache,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      fileSystemAccessCache: {
        backend: common.fileSystemAccessCache,
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      executeAuthorizer: { allow: {} },
    }
  runner-ubuntu22-04.jsonnet: |
    local common = import 'common.libsonnet';

    {
      buildDirectoryPath: '/worker/build',
      // TODO: global: common.global,
      grpcServers: [{
        listenPaths: ['/worker/runner'],
        authenticationPolicy: { allow: {} },
      }],
    }
  scheduler.jsonnet: |
    local common = import 'common.libsonnet';

    {
      adminHttpServers: [{
        listenAddresses: [':7982'],
        authenticationPolicy: { allow: {} },
      }],
      clientGrpcServers: [{
        listenAddresses: [':8982'],
        authenticationPolicy: { allow: {} },
      }],
      workerGrpcServers: [{
        listenAddresses: [':8983'],
        authenticationPolicy: { allow: {} },
      }],
      buildQueueStateGrpcServers: [{
        listenAddresses: [':8984'],
        authenticationPolicy: { allow: {} },
      }],
      browserUrl: common.browserUrl,
      contentAddressableStorage: common.blobstore.contentAddressableStorage,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      executeAuthorizer: { allow: {} },
      modifyDrainsAuthorizer: { allow: {} },
      killOperationsAuthorizer: { allow: {} },
      synchronizeAuthorizer: { allow: {} },
      actionRouter: {
        simple: {
          platformKeyExtractor: { action: {} },
          invocationKeyExtractors: [
            { correlatedInvocationsId: {} },
            { toolInvocationId: {} },
          ],
          initialSizeClassAnalyzer: {
            defaultExecutionTimeout: '1800s',
            maximumExecutionTimeout: '7200s',
          },
        },
      },
      platformQueueWithNoWorkersTimeout: '900s',
    }
  storage.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8981'],
        authenticationPolicy: { allow: {} },
      }],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      contentAddressableStorage: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-cas/key_location_map',
                sizeBytes: 400 * 1024 * 1024,
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 3,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-cas/blocks',
                  sizeBytes: 32 * 1024 * 1024 * 1024,
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-cas/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
        findMissingAuthorizer: { allow: {} },
      },
      actionCache: {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-ac/key_location_map',
                sizeBytes: 1024 * 1024,
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-ac/blocks',
                  sizeBytes: 20 * 1024 * 1024,
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-ac/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
      fileSystemAccessCache:  {
        backend: {
          'local': {
            keyLocationMapOnBlockDevice: {
              file: {
                path: '/storage-fsac/key_location_map',
                sizeBytes: 1024 * 1024,
              },
            },
            keyLocationMapMaximumGetAttempts: 16,
            keyLocationMapMaximumPutAttempts: 64,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
              source: {
                file: {
                  path: '/storage-fsac/blocks',
                  sizeBytes: 20 * 1024 * 1024,
                },
              },
              spareBlocks: 3,
            },
            persistent: {
              stateDirectoryPath: '/storage-fsac/persistent_state',
              minimumEpochInterval: '300s',
            },
          },
        },
        getAuthorizer: { allow: {} },
        putAuthorizer: { allow: {} },
      },
    }
  worker-ubuntu22-04.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      browserUrl: common.browserUrl,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      scheduler: { address: 'scheduler:8983' },
      global: common.global {
        setUmask: { umask: 0 },
      },
      buildDirectories: [{
        native: {
          buildDirectoryPath: '/worker/build',
          cacheDirectoryPath: '/worker/cache',
          maximumCacheFileCount: 10000,
          maximumCacheSizeBytes: 1024 * 1024 * 1024,
          cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
        },
        runners: [{
          endpoint: { address: 'unix:///worker/runner' },
          concurrency: 8,
          platform: {
            properties: [
              { name: 'OSFamily', value: 'linux' },
              { name: 'container-image', value: 'docker://ghcr.io/catthehacker/ubuntu:act-22.04@sha256:dd7654ffb01d5b7b54b23b9ce928a1f7f2d08c7b3d7e320b6574b55d7ccde78b' },
            ],
          },
          workerId: {
            pod: std.extVar('POD_NAME'),
            node: std.extVar('NODE_NAME'),
          },
        }],
      }],
      inputDownloadConcurrency: 10,
      outputUploadConcurrency: 11,
      directoryCache: {
        maximumCount: 1000,
        maximumSizeBytes: 1000 * 1024,
        cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
      },
    }
kind: ConfigMap
metadata:
  annotations:
      {"apiVersion":"v1","data":{"browser.jsonnet":"local common = import 'common.libsonnet';\n\n{\n  blobstore: common.blobstore,\n  maximumMessageSizeBytes: common.maximumMessageSizeBytes,\n  httpServers: [{\n    listenAddresses: [':7984'],\n    authenticationPolicy: { allow: {} },\n  }],\n  global: common.global,\n  authorizer: { allow: {} },\n  requestMetadataLinksJmespathExpression: { expression: '`{}`' },\n}\n","common.libsonnet":"{\n  blobstore: {\n    contentAddressableStorage: {\n      sharding: {\n        shards: {\n          \"0\": {\n            backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },\n            weight: 1,\n          },\n          \"1\": {\n            backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },\n            weight: 1,\n          },\n        },\n      },\n    },\n    actionCache: {\n      completenessChecking: {\n        backend: {\n          sharding: {\n            shards: {\n              \"0\": {\n                backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },\n                weight: 1,\n              },\n              \"1\": {\n                backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },\n                weight: 1,\n              },\n            },\n          },\n        },\n        maximumTotalTreeSizeBytes: 64 * 1024 * 1024,\n      },\n    },\n  },\n  fileSystemAccessCache: {\n    sharding: {\n      shards: {\n        \"0\": {\n          backend: { grpc: { client: { address: 'storage-0.storage.buildbarn:8981' } } },\n          weight: 1,\n        },\n        \"1\": {\n          backend: { grpc: { client: { address: 'storage-1.storage.buildbarn:8981' } } },\n          weight: 1,\n        },\n      },\n    },\n  },\n  browserUrl: 'http://bb-browser.example.com:80',\n  maximumMessageSizeBytes: 2 * 1024 * 1024,\n  global: {\n    diagnosticsHttpServer: {\n      httpServers: [{\n        listenAddresses: [':9980'],\n        authenticationPolicy: { allow: {} },\n      }],\n      enablePrometheus: true,\n      enablePprof: true,\n      enableActiveSpans: true,\n    },\n  },\n}\n","frontend.jsonnet":"local common = import 'common.libsonnet';\n\n{\n  grpcServers: [{\n    listenAddresses: [':8980'],\n    authenticationPolicy: { allow: {} },\n  }],\n  schedulers: {\n    '': {\n      endpoint: {\n        address: 'scheduler:8982',\n        addMetadataJmespathExpression: {\n          expression: |||\n            {\n              \"build.bazel.remote.execution.v2.requestmetadata-bin\": incomingGRPCMetadata.\"build.bazel.remote.execution.v2.requestmetadata-bin\"\n            }\n          |||,\n        },\n      },\n    },\n  },\n  maximumMessageSizeBytes: common.maximumMessageSizeBytes,\n  global: common.global,\n  contentAddressableStorage: {\n    backend: common.blobstore.contentAddressableStorage,\n    getAuthorizer: { allow: {} },\n    putAuthorizer: { allow: {} },\n    findMissingAuthorizer: { allow: {} },\n  },\n  actionCache: {\n    backend: common.blobstore.actionCache,\n    getAuthorizer: { allow: {} },\n    putAuthorizer: { allow: {} },\n  },\n  fileSystemAccessCache: {\n    backend: common.fileSystemAccessCache,\n    getAuthorizer: { allow: {} },\n    putAuthorizer: { allow: {} },\n  },\n  executeAuthorizer: { allow: {} },\n}\n","runner-ubuntu22-04.jsonnet":"local common = import 'common.libsonnet';\n\n{\n  buildDirectoryPath: '/worker/build',\n  // TODO: global: common.global,\n  grpcServers: [{\n    listenPaths: ['/worker/runner'],\n    authenticationPolicy: { allow: {} },\n  }],\n}\n","scheduler.jsonnet":"local common = import 'common.libsonnet';\n\n{\n  adminHttpServers: [{\n    listenAddresses: [':7982'],\n    authenticationPolicy: { allow: {} },\n  }],\n  clientGrpcServers: [{\n    listenAddresses: [':8982'],\n    authenticationPolicy: { allow: {} },\n  }],\n  workerGrpcServers: [{\n    listenAddresses: [':8983'],\n    authenticationPolicy: { allow: {} },\n  }],\n  buildQueueStateGrpcServers: [{\n    listenAddresses: [':8984'],\n    authenticationPolicy: { allow: {} },\n  }],\n  browserUrl: common.browserUrl,\n  contentAddressableStorage: common.blobstore.contentAddressableStorage,\n  maximumMessageSizeBytes: common.maximumMessageSizeBytes,\n  global: common.global,\n  executeAuthorizer: { allow: {} },\n  modifyDrainsAuthorizer: { allow: {} },\n  killOperationsAuthorizer: { allow: {} },\n  synchronizeAuthorizer: { allow: {} },\n  actionRouter: {\n    simple: {\n      platformKeyExtractor: { action: {} },\n      invocationKeyExtractors: [\n        { correlatedInvocationsId: {} },\n        { toolInvocationId: {} },\n      ],\n      initialSizeClassAnalyzer: {\n        defaultExecutionTimeout: '1800s',\n        maximumExecutionTimeout: '7200s',\n      },\n    },\n  },\n  platformQueueWithNoWorkersTimeout: '900s',\n}\n","storage.jsonnet":"local common = import 'common.libsonnet';\n\n{\n  grpcServers: [{\n    listenAddresses: [':8981'],\n    authenticationPolicy: { allow: {} },\n  }],\n  maximumMessageSizeBytes: common.maximumMessageSizeBytes,\n  global: common.global,\n  contentAddressableStorage: {\n    backend: {\n      'local': {\n        keyLocationMapOnBlockDevice: {\n          file: {\n            path: '/storage-cas/key_location_map',\n            sizeBytes: 400 * 1024 * 1024,\n          },\n        },\n        keyLocationMapMaximumGetAttempts: 16,\n        keyLocationMapMaximumPutAttempts: 64,\n        oldBlocks: 8,\n        currentBlocks: 24,\n        newBlocks: 3,\n        blocksOnBlockDevice: {\n          source: {\n            file: {\n              path: '/storage-cas/blocks',\n              sizeBytes: 32 * 1024 * 1024 * 1024,\n            },\n          },\n          spareBlocks: 3,\n        },\n        persistent: {\n          stateDirectoryPath: '/storage-cas/persistent_state',\n          minimumEpochInterval: '300s',\n        },\n      },\n    },\n    getAuthorizer: { allow: {} },\n    putAuthorizer: { allow: {} },\n    findMissingAuthorizer: { allow: {} },\n  },\n  actionCache: {\n    backend: {\n      'local': {\n        keyLocationMapOnBlockDevice: {\n          file: {\n            path: '/storage-ac/key_location_map',\n            sizeBytes: 1024 * 1024,\n          },\n        },\n        keyLocationMapMaximumGetAttempts: 16,\n        keyLocationMapMaximumPutAttempts: 64,\n        oldBlocks: 8,\n        currentBlocks: 24,\n        newBlocks: 1,\n        blocksOnBlockDevice: {\n          source: {\n            file: {\n              path: '/storage-ac/blocks',\n              sizeBytes: 20 * 1024 * 1024,\n            },\n          },\n          spareBlocks: 3,\n        },\n        persistent: {\n          stateDirectoryPath: '/storage-ac/persistent_state',\n          minimumEpochInterval: '300s',\n        },\n      },\n    },\n    getAuthorizer: { allow: {} },\n    putAuthorizer: { allow: {} },\n  },\n  fileSystemAccessCache:  {\n    backend: {\n      'local': {\n        keyLocationMapOnBlockDevice: {\n          file: {\n            path: '/storage-fsac/key_location_map',\n            sizeBytes: 1024 * 1024,\n          },\n        },\n        keyLocationMapMaximumGetAttempts: 16,\n        keyLocationMapMaximumPutAttempts: 64,\n        oldBlocks: 8,\n        currentBlocks: 24,\n        newBlocks: 1,\n        blocksOnBlockDevice: {\n          source: {\n            file: {\n              path: '/storage-fsac/blocks',\n              sizeBytes: 20 * 1024 * 1024,\n            },\n          },\n          spareBlocks: 3,\n        },\n        persistent: {\n          stateDirectoryPath: '/storage-fsac/persistent_state',\n          minimumEpochInterval: '300s',\n        },\n      },\n    },\n    getAuthorizer: { allow: {} },\n    putAuthorizer: { allow: {} },\n  },\n}\n","worker-ubuntu22-04.jsonnet":"local common = import 'common.libsonnet';\n\n{\n  blobstore: common.blobstore,\n  browserUrl: common.browserUrl,\n  maximumMessageSizeBytes: common.maximumMessageSizeBytes,\n  scheduler: { address: 'scheduler:8983' },\n  global: common.global {\n    setUmask: { umask: 0 },\n  },\n  buildDirectories: [{\n    native: {\n      buildDirectoryPath: '/worker/build',\n      cacheDirectoryPath: '/worker/cache',\n      maximumCacheFileCount: 10000,\n      maximumCacheSizeBytes: 1024 * 1024 * 1024,\n      cacheReplacementPolicy: 'LEAST_RECENTLY_USED',\n    },\n    runners: [{\n      endpoint: { address: 'unix:///worker/runner' },\n      concurrency: 8,\n      platform: {\n        properties: [\n          { name: 'OSFamily', value: 'linux' },\n          { name: 'container-image', value: 'docker://ghcr.io/catthehacker/ubuntu:act-22.04@sha256:dd7654ffb01d5b7b54b23b9ce928a1f7f2d08c7b3d7e320b6574b55d7ccde78b' },\n        ],\n      },\n      workerId: {\n        pod: std.extVar('POD_NAME'),\n        node: std.extVar('NODE_NAME'),\n      },\n    }],\n  }],\n  inputDownloadConcurrency: 10,\n  outputUploadConcurrency: 11,\n  directoryCache: {\n    maximumCount: 1000,\n    maximumSizeBytes: 1000 * 1024,\n    cacheReplacementPolicy: 'LEAST_RECENTLY_USED',\n  },\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"buildbarn-config-g99g2mcfg6","namespace":"buildbarn"}}
  name: buildbarn-config-g99g2mcfg6
  namespace: buildbarn
