name: aurora
min-version: "2.5"
element-path: elements

(@):
  - kde-build-meta.bst:freedesktop-sdk.bst:include/runtime.yml
  - include/aliases.yml

options:
  arch:
    type: arch
    description: Machine architecture
    variable: arch
    values:
      - aarch64
      - x86_64

sandbox:
  build-arch: "%{arch}"

variables:
  branch: main

plugins:
- origin: junction
  junction: kde-build-meta.bst:plugins/buildstream-plugins.bst
  elements:
    - autotools
    - meson
    - cmake
    - make
  sources:
    - patch
    - git

- origin: junction
  junction: kde-build-meta.bst:plugins/buildstream-plugins-community.bst
  elements:
    - collect_integration
  sources:
    - git_repo
