kind: stack
description: KDE Plasma Desktop

depends:
- kde/org.kde.Sdk.bst
- kde/plasma/aurorae.bst
- kde/plasma/breeze.bst
- kde/plasma/kactivitymanagerd.bst
- kde/plasma/kdecoration.bst
- kde/plasma/kdeplasma-addons.bst
- kde/plasma/kglobalacceld.bst
- kde/plasma/kinfocenter.bst
- kde/plasma/knighttime.bst
- kde/plasma/konsole.bst
- kde/plasma/kpipewire.bst
- kde/plasma/kscreenlocker.bst
- kde/plasma/kwayland.bst
- kde/plasma/kwin.bst
- kde/plasma/layer-shell-qt.bst
- kde/plasma/libkscreen.bst
- kde/plasma/libksysguard.bst
- kde/plasma/libplasma.bst
- kde/plasma/milou.bst
- kde/plasma/plasma-activities-stats.bst
- kde/plasma/plasma-activities.bst
- kde/plasma/plasma-desktop.bst
- kde/plasma/plasma-integration.bst
- kde/plasma/plasma-nano.bst
- kde/plasma/plasma-nm.bst
- kde/plasma/plasma-workspace.bst
- kde/plasma/plasma5support.bst
- kde/plasma/powerdevil.bst
- kde/plasma/qqc2-breeze-style.bst
- kde/plasma/spectacle.bst
- kde/plasma/systemsettings.bst
